spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/hawaste?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #设置模板
  thymeleaf:
    prefix: classpath:/templates/
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
minio:
  bucketName: uploads # 存储桶名字
  endpoint: 127.0.0.1 #桶所在节点ip
  port: 9000      # web管理服务访问端口
  secure: false  #false为http   true为 https
  accessKey: minioadmin #登录账号
  secretKey: minioadmin #密码
pic:
  prefix: http://localhost:80/file #图片访问路径前缀
shiro:
  loginUrl: /notlogin.html #未认证用户跳转到登录的页面请求
  successUrl: /         #认证成功用户的跳转页面请求地址
  unauthorizedUrl: /notauth.html #无访问权限用户的请求跳转地址